/*
SOLUTION OF THE LINEAR MIN-SUM ASSIGNMENT PROBLEM. 
*/

#ifndef APC_H
#define APC_H

#ifdef __cplusplus
extern "C" {
#endif


/*
       
 SOLUTION OF THE LINEAR MIN-SUM ASSIGNMENT PROBLEM.                         

 MEANING OF THE INPUT PARAMETERS:          
 n       = NUMBER OF ROWS AND COLUMNS OF THE COST MATRIX.     
 a[i][j] = COST OF THE ASSIGNMENT OF ROW  i  TO COLUMN  j .   
 INF     = A VERY LARGE INTEGER VALUE, SETTED BY THE USER ACCORDING TO THE CHARACTERISTICS OF THE USED MACHINE.
		   INF IS THE ONLY MACHINE-DEPENDENT CONSTANT USED AND IT MUST BE STRICTLY GREATER THAN THE MAXIMUM 
		   ASSIGNMENT COST (E.G., INF MUST BE STRICTLY GREATER THAN THE MAXIMUM VALUE OF THE COST MATRIX a).
 ON RETURN, THE INPUT PARAMETERS ARE UNCHANGED.              
       
 MEANING OF THE OUTPUT PARAMETERS:       
 f[i] = COLUMN ASSIGNED TO ROW i.        
 z_p  = COST OF THE OPTIMAL ASSIGNMENT =   
      = a[0][f[0]] + a[1][f[1]] + ... + a[n-1][f[n-1]] .  
	  
 RETURN VALUE:
 0,  IF THE PROBLEM HAS BEEN SOLVED AND THE OUTPUT PARAMETERS HAVE BEEN PROPERLY SETTED
 -1, IF THE PROBLEM HAS NOT BEEN SOLVED DUE TO A MEMORY ISSUE (NOT ENOUGH AVAILABLE MEMORY)
       
 ALL THE PARAMETERS ARE INTEGERS.
 VECTOR  f  MUST BE DIMENSIONED AT LEAST AT  n , MATRIX  a
 AT LEAST AT  (n,n) . 
       
*/
int apc(int n,int **a,int INF,int *z_p,int *f, double* sum);



#ifdef __cplusplus
}
#endif


#endif

